version: '2.1'
orbs:
  node: circleci/node@x.y
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --versios
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: sudo npm install -g npm@latest
      - run: npm run test
   
workflows:
  test_my_app:
    jobs:
      - install-node-example
      - node/test:
          test-results-for: jest
      - node/run:
          npm-run: build
      - node/test
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - main
          requires:
            - node/test
      - node/run:
          yarn-run: build
      - test
      
      
